import { Platform } from 'react-native';
import { RFPercentage, RFValue } from "react-native-responsive-fontsize";

var decreaseFontBy = 0;
export default (Theme = {
  colors: {
    sendMeBlue: "#05C2F0",
    sendMeBlack: '#1A1311',
    sendMeGray: "#8D9496"
  },
  fontFamily: {
    black: 'Rubik-Black',
    black_italic: 'Rubik-BlackItalic',
    bold: "Rubik-Bold",
    bold_italic: "Rubik-BoldItalic",
    italic: 'Rubik-Italic',
    light: 'Rubik-Light',
    light_italic: 'Rubik-LightItalic',
    medium: 'Rubik-Medium',
    medium_italic: 'Rubik-MediumItalic',
    regular: "Rubik-Regular",
  },
  fontSize: {
    extraLarge: RFValue(44 - decreaseFontBy),
    mediumLargeX: RFValue(38 - decreaseFontBy),
    mediumLarge: RFValue(34 - decreaseFontBy),
    largeX: RFValue(30 - decreaseFontBy),
    large: RFValue(26 - decreaseFontBy),
    semiLarge: RFValue(24 - decreaseFontBy),
    medium: RFValue(22 - decreaseFontBy),
    semiMedium: RFValue(20 - decreaseFontBy),
    regularX: RFValue(19 - decreaseFontBy),
    regular: RFValue(18 - decreaseFontBy),
    semiRegular: RFValue(16.5 - decreaseFontBy),
    small: RFValue(15 - decreaseFontBy),
    semiSmall1: RFValue(14 - decreaseFontBy),
    semiSmall: RFValue(13 - decreaseFontBy),
    semi_Small: RFValue(12 - decreaseFontBy),
    extraSmall: RFValue(11 - decreaseFontBy),
    veryExtraSmall: RFValue(9 - decreaseFontBy),
  },
  fontSize1: {
    extraLarge: RFValue(44 - decreaseFontBy),
    mediumLargeX: RFValue(38 - decreaseFontBy),
    mediumLarge: RFValue(34 - decreaseFontBy),
    largeX: RFValue(30 - decreaseFontBy),
    large: RFValue(26 - decreaseFontBy),
    semiLarge: RFValue(24 - decreaseFontBy),
    medium: RFValue(22 - decreaseFontBy),
    semiMedium: RFValue(20 - decreaseFontBy),
    regularX: RFValue(19 - decreaseFontBy),
    regular: RFValue(18 - decreaseFontBy),
    semiRegular: RFValue(16.5 - decreaseFontBy),
    small: RFValue(15 - decreaseFontBy),
    semiSmall1: RFValue(14 - decreaseFontBy),
    semiSmall: RFValue(13 - decreaseFontBy),
    semi_Small: RFValue(12 - decreaseFontBy),
    extraSmall: RFValue(11 - decreaseFontBy),
    veryExtraSmall: RFValue(9 - decreaseFontBy),
  },
  icons: {
    img_splashscreen: require('../Resources/imageAssets/splashscreen/slpashscreen.png'),
    ic_sidemenu: require('../Resources/imageAssets/ic_sidemenu/ic_sidemenu.png'),
    ic_app_logo: require('../Resources/imageAssets/app_logo/app_logo.png'),
    ic_unchecked: require('../Resources/imageAssets/ic_unchecked/ic_unchecked.png'),
    ic_checked: require('../Resources/imageAssets/ic_checked/ic_checked.png'),
    ic_missionaries: require('../Resources/imageAssets/ic_missionaries/ic_missionaries.png'),
    ic_sponsor: require('../Resources/imageAssets/ic_sponsor/ic_sponsor.png'),
    ic_step_next_arrow: require('../Resources/imageAssets/ic_step_next_arrow/ic_step_next_arrow.png'),
    ic_mission: require('../Resources/imageAssets/ic_mission/ic_mission.png'),
    ic_drop_down: require('../Resources/imageAssets/ic_drop_down/ic_drop_down.png'),
    ic_right_arrow: require('../Resources/imageAssets/ic_right_arrow/ic_right_arrow.png'),
    ic_go_back: require('../Resources/imageAssets/ic_go_back/ic_go_back.png'),
    ic_search: require('../Resources/imageAssets/ic_search/ic_search.png'),
    ic_orientation: require('../Resources/imageAssets/ic_orientation/ic_orientation.png'),

    ic_radio_checked: require('../Resources/imageAssets/ic_radio_checked/ic_radio_checked.png'),
    ic_radio_unchecked: require('../Resources/imageAssets/ic_radio_unchecked/ic_radio_unchecked.png'),
    ic_home: require('../Resources/imageAssets/ic_home/ic_home.png'),

    ic_help_hand: require('../Resources/imageAssets/ic_help_hand/ic_help_hand.png'),
    ic_news_feed: require('../Resources/imageAssets/ic_news_feed/ic_news_feed.png'),
    ic_read_book: require('../Resources/imageAssets/ic_read_book/ic_read_book.png'),
    ic_logout: require('../Resources/imageAssets/ic_logout/ic_logout.png'),
    ic_user: require('../Resources/imageAssets/ic_user/ic_user.png'),
    ic_list: require('../Resources/imageAssets/ic_list/ic_list.png'),

    ic_about_us: require('../Resources/imageAssets/ic_about_us/ic_about_us.png'),
    ic_settings: require('../Resources/imageAssets/ic_settings/ic_settings.png'),
    ic_phone: require('../Resources/imageAssets/ic_phone/ic_phone.png'),

    ic_plus_add: require('../Resources/imageAssets/ic_plus_add/ic_plus_add.png'),
    ic_delete: require('../Resources/imageAssets/ic_delete/ic_delete.png'),
    ic_dots: require('../Resources/imageAssets/ic_dots/ic_dots.png'),
    ic_donation: require('../Resources/imageAssets/ic_donation/ic_donation.png'),

    ic_user_profile: require('../Resources/imageAssets/ic_user_profile/ic_user_profile.png'),

    ic_bank: require('../Resources/imageAssets/ic_bank/ic_bank.png'),
    ic_credit_card: require('../Resources/imageAssets/ic_credit_card/ic_credit_card.png'),

    ic_close: require('../Resources/imageAssets/ic_close/ic_close.png'),
    ic_correct: require('../Resources/imageAssets/ic_correct/ic_correct.png'),
    ic_share: require('../Resources/imageAssets/ic_share/ic_share.png'),
    ic_share_message: require('../Resources/imageAssets/ic_share_message/ic_share_message.png'),
    ic_reload: require('../Resources/imageAssets/ic_reload/ic_reload.png'),
    ic_admin: require('../Resources/imageAssets/ic_admin/ic_admin.png'),
  }
});
