export default (AppConstants = {
    AlertDefaultTitle: "SendMe",
    errorAlertDefaultTitle: "Oops! An error occured.",
    api_dev_secret_key: "Kv9TnOO9o5Q2QG2e8cKv5uqub",
    plaid_public_key_dev: "2f07030525f95181721ef3783e9774", // 2f07030525f95181721ef3783e9774 => LIVE
    loaderTimeOutDuration: 40,
    StringLiterals: {
        strBundleKeyDev_Android: "com.app.sendme.dev",
        strBundleKeyDev_iOS: "com.app.sendme.dev",
        strBundleKeyLive_Android: "com.app.sendme",
        strBundleKeyLive_iOS: "com.app.sendme",
        strServerConfigurationURL: "https://sendme.club/api/load_app_config.php",
        strPasswordDoesnNotMatch: "Password and confirm password doesn't match.",
        strPasswordFailMinCharacter: "Password should be minimum 5 characters long and must contains 1 digit.",
        strPasswordFailNumberCharacter: "Password must have 1 digit.",
        strEmailFormatFail: "Please enter valid email address.",
        strAdditionalEmailFormatFail: "Please enter valid additional email address.",
        strErrorWhileCreatingUser: "There was an error trying to create your account. Please try again later.",
        strErrorWhileLoadingPayment: "There was an error trying to load payment status. Please try again later.",
        strErrorWhileFetchingGig: "There was an error trying to fetch gigs. Please try again later.",
        strErrorWhilePostingGig: "There was an error trying to post a gig. Please try again later.",
        strHearAboutTextPlaceHolder: "How did you hear about us?",
        strProfilePicture: "You must provide a profile picture.",
        strReferenceNeededTitle: "References Needed",
        strReferenceNeededValue: "You must provide at least one reference. References will remain confidential and will only be used for verification.",
        strExterShoreGigNotes: "Please place the location where you will be in the notes below",
        strPromoCodeNotes: "Total does not reflect gift card/discounted rates",
        strNoSitterPost: "NO CURRENT SITTER POSTS",
        strNoFamilyPost: "NO CURRENT FAMILY POSTS",
        strNoHistory: "YOU DO NOT HAVE ANY HISTORY",
        strStartTimeShouldBeGrater: "Start time can't be less then current time.",
        strErrorPaymentSourceNotFound: "Please setup payment source to post a gig.",
        strErrorPaymentSourceNotVerified: "Your default payment source is not verified. You should verify it before requesting gig!\n\nCurrent status: ",
        strRequestBookingConfirm: "Are you sure you would like to request this booking?",
        strErrorGeneral: "An error occurred while trying to make a request.  Please try again later.",
        strErrorBookingFail: "An error occurred while trying to save your request.  Please try again later.",
        strErrorBookingRequestCancelFail: "An error occurred while trying to remove your request.  Please try again later.",
        strRequestBookingRequestSent: "Request has been made. You will be notified when the request has been accepted.",
        strRequestBookingRequestCancelled: "Your request has been cancelled.",
        strRequestBookingRemove: "Are you sure you would like to cancel your booking request?",
        strReportUserTitle: "Report User?",
        strReportUserMessage: "Are you sure you would like to report this user's profile as inappropriate?",
        strUserReported: "Reported user successfully",
        strLogoutConfirm: "Are you sure you want to logout?",
        strDeleteAccount: "Are you sure you want to delete account? Your account will be permanently delete and can't be rollback.",
        strStayLoggedIn: "Stay Logged In",
        strCalculatingDistance: "Calculating...",
        selectDateOfBirth: "Please select date of birth",
        selectChildDateOfBirth: "Please select child date of birth",
        strCodePushKey_DEV_Android: "aVBQQw-lCKGBCwCiRYiUz2k-R9ugH8I5VJFlC",
        strCodePushKey_DEV_iOS: "GXfe4O1IYeoEpG6W2LV5Kl5-qQlAscIz2oOEW",

        strCodePushKey_LIVE_Android: "ylcgPWZIQj9VDqUuHHqUxVgHjellIhTWMHRre",
        strCodePushKey_LIVE_iOS: "pk8U79hWBpWcmtuYb4yPvT-EZac6Vdp4_dKvV",

        kCachedLocations: "kCachedLocations12",
        kCachedCoordinateForAddress: "kCachedCoordinateForAddress",
        strServerServiceError: "We are sorry there was an issue connecting to the service",
        rasingPausedMessage: "Raising money has been paused.",
        missionaryRaisingFundPaused: "has paused raising funds. Please choose another missionary to send funds!",
        strAddBankSponsorTos: "- The sponsor's bank account will initiate payments every other Friday for the total amount of spare change rounded up in the account. If the amount is lower than $10, the payment will not process until the account reaches a minimum of $10.\n\n- A sponsor can also send a one-time payment in addition to round up payments at any time.\n\n- The sponsor must pause their payments in order to stop payments from being initiated. If payments are not paused, the payments will be initiated during schedule periods of every other Friday.\n\n- If a missionary, pauses or deactivates there account, the Sponsor's payments will be paused and the payments will not resume unless the account/mission are reactivated.\n\n- The missionary will receive 90% of each payment and 10% will be sent to SendMe to cover Stripe fees, Plaid fees, and admin fees. This is for both round up and one-time payments.",
        errPlaidLoginRequiredError: "There is an issue with your current credit card set-up. Please sign into the same account through Plaid or you can always try a different account. Please select contact us in the menu and send us a message if the issue persists. Thanks!"
    },
    AsyncKeyLiterals: {
        strConfigData: "strConfigData",
        strCurrentUserData: "strCurrentUserData",
        strCurrentUserToken: "strCurrentUserToken",
        strIsNappNotesSeenFirstTime: "strIsNappNotesSeenFirstTime",
        strIsNappNotesSeenFirstTimeAfterApproved: "strIsNappNotesSeenFirstTimeAfterApproved",
        strLiveGigAutoNavigation: "strLiveGigAutoNavigation",
        kPushToken: "kPushToken",
        strInviteContact: "strInviteContact"
    }
})